title = "ICAPEG configuration file"

[app]
debug = true
port = 1344
http_port = 8080
max_filesize = 10000000 #bytes
scanner_vendor = "virustotal" # Supported vendors "virustotal", "metadefender" , "vmray"
unprocessable_content_types = ["application/gzip" , "text/html" , "image/jpeg" , "image/png"]
unprocessable_extensions = [".gz" , ".png" , ".jpg" , ".jpeg" , ".html"]
processable_extensions = ["*"  , ".txt" , ".pdf" , ".dmg" , "unknown"] # * = all extensions, unknown = system couldn't find out the type of the file
preview_bytes = "4096" #bytes
propagate_error = true
local_scanner = false



[virustotal]
base_url = "https://www.virustotal.com/vtapi/v2"
file_scan_endpoint = "/file/scan"
url_scan_endpoint = "/url/scan"
file_report_endpoint = "/file/report?apikey=%s&resource=%s"
url_report_endpoint = "/url/report?apikey=%s&resource=%s"
api_key = "44904fa3f2b4c03295d4e83b3a183f786a542837b120d1c0eddcaa96cf0f42c9"
timeout  = 10 #seconds
fail_threshold = 2
status_check_interval = 2 #seconds, the time interval after which the submission status check will be called
status_check_timeout = 300 #seconds, the total time duration after which the the status check should be stopped, if not finished
bad_file_status = ["malicious"]
ok_file_status = ["ok"]
status_endpoint_exists = false #this field determines whether the scanner vendor has any status check endpoint or not

[metadefender]
base_url = "https://api.metadefender.com/v4"
scan_endpoint = "/file"
report_endpoint = "/file"
api_key = "<Your metadefender API KEY here>"
timeout  = 10 #seconds
fail_threshold = 2
status_check_interval = 2 #seconds, the time interval after which the submission status check will be called
status_check_timeout = 300 #seconds, the total time duration after which the the status check should be stopped, if not finished
bad_file_status = ["malicious"]
ok_file_status = ["ok"]
status_endpoint_exists = false #this field determines whether the scanner vendor has any status check endpoint or not

[vmray]
base_url = "https://cloud.vmray.com/rest"
submit_endpoint = "/sample/submit"
get_sample_endpoint= "/sample"
submission_status_endpoint = "/submission"
timeout = 10 #seconds , the timeout duration for all the api calls for vmray
status_check_interval = 2 #seconds, the time interval after which the submission status check will be called
status_check_timeout = 300 #seconds, the total time duration after which the the status check should be stopped, if not finished
bad_file_status = ["malicious", "suspicious", "blacklisted"]
ok_file_status = ["not_suspicious" , "whitelisted", "unknown"]
api_key = "<Your vmray API KEY here>"
status_endpoint_exists = true


[clamav]
socket_path = "/var/run/clamav/clamd.ctl"
wait_timeout = 10 #seconds, the time upto which the server will wait for clamav to scan the results
bad_file_status = ["malicious"]
ok_file_status = ["ok"]
